
name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and push Docker images
        uses: docker/build-push-action@2.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: | 
            williammedeiros007/rotten-potatoes:latest
            williammedeiros007/rotten-potatoes:${{ github_run_number }}


 
          
